spring:
  application:
    name: demo

server:
  port: 8081
  servlet:
    contextPath: /demo

javastack:
  name: java
  site: www.java
  author: au
  users:
    - Jom
    - Lucy
    - Jack
  params:
    tel: 18
    address: tai
  security:
    security-key: 123
    security-code: 666